Arithmetic Operations

In [12]:
import numpy as np

In [13]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

In [14]:
#sum of two arrays
sum_arr = arr1 + arr2
sum_arr

array([ 7,  9, 11, 13, 15])

In [15]:
#subtraction of two arrays
sub_arr = arr1 - arr2
sub_arr

array([-5, -5, -5, -5, -5])

In [16]:
#multiplication of two arrays
mul_arr = arr1 * arr2
mul_arr

array([ 6, 14, 24, 36, 50])

In [17]:
#boolean operations
bool_arr = arr1 > 3
bool_arr

array([False, False, False,  True,  True])

Broadcasting

In [18]:
arr1 + 10

array([11, 12, 13, 14, 15])

Delete and Shallow Copy

In [19]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [21]:
slice = a[1:3]
slice *10

array([20, 30])

In [ ]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
#a@b uses matrix multiplication
a@b

np.int64(70)

In [23]:
a.dot(b)

np.int64(70)

Stacking array

In [24]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [25]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

Splitting array

In [28]:
np.split(a, 2)

[array([1, 2]), array([3, 4])]