In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [3]:
#indexing
arr[0] #first element

np.int64(1)

In [4]:
arr[:2] #first two elements

array([1, 2])

In [5]:
arr[:-1] #all elements except the last one

array([1, 2, 3])

In [6]:
arr[0:2] #first two elements

array([1, 2])

In [7]:
arr[::-1] #reverse the array

array([4, 3, 2, 1])

Numpy indexing and slicing of matrix

In [8]:
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arr[2] #last row

array([7, 8, 9])

In [10]:
arr[1,1] #element at row 1 and column 1

np.int64(5)

In [13]:
arr[0:2,0:2] #first two rows and first two columns

array([[1, 2],
       [4, 5]])

In [14]:
#boolean indexing
arr= np.arange(1,13)
boolean_arr = arr > 5
boolean_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True])

In [ ]:
#filtering the array using boolean indexing
arr =arr[boolean_arr]
arr

array([ 6,  7,  8,  9, 10, 11, 12])